# Configuration/Services.yaml
services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  OliverThiele\OtFaq\:
    resource: '../Classes/*'
    exclude: '../Classes/Domain/Mode/*'
